/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.33
 * Generated at: 2016-06-13 16:15:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class admin_005fDoctor_005fReservation_005fConfrim_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');


String doc_id = request.getParameter("doc_id");
String id = request.getParameter("id");
String date = request.getParameter("date");
String email = request.getParameter("email");
String subject = request.getParameter("subject");


      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\" lang=\"ko\" xml:lang=\"ko\">\r\n");
      out.write("  <head>\r\n");
      out.write("  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=euc-kr\">\r\n");
      out.write("  <script type=\"text/javaScript\">\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\tfunction Windowclose(){\r\n");
      out.write("\t\twindow.opener='Self';\r\n");
      out.write("\t\twindow.open('','_parent','');\r\n");
      out.write("\t\twindow.close();\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction submitForm(X,y){\r\n");
      out.write("\t\t X.action = y;\r\n");
      out.write("\t\t X.method=\"get\";\r\n");
      out.write("\t\t X.encoding =\"multipart/form-data\";\r\n");
      out.write("\t\t X.submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"\">\r\n");
      out.write("    <link rel=\"icon\" href=\"../../favicon.ico\">\r\n");
      out.write("\r\n");
      out.write("    <title>예약내역</title>\r\n");
      out.write("\r\n");
      out.write("<!-- 합쳐지고 최소화된 최신 CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- 부가적인 테마 -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- 합쳐지고 최소화된 최신 자바스크립트 -->\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom styles for this template -->\r\n");
      out.write("    <link href=\"signin.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->\r\n");
      out.write("    <!--[if lt IE 9]><script src=\"../../assets/js/ie8-responsive-file-warning.js\"></script><![endif]-->\r\n");
      out.write("    <script src=\"../../assets/js/ie-emulation-modes-warning.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("    <!--[if lt IE 9]>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js\"></script>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("   \r\n");
      out.write("   <article class=\"container\">      \r\n");
      out.write("        <div class=\"col-md-12\">\r\n");
      out.write("        <div class=\"page-header\">\r\n");
      out.write("    \t    <h1>의사 ");
      out.print(doc_id );
      out.write("님 예약 내역</h1>\r\n");
      out.write("        </div>\r\n");
      out.write("                \r\n");
      out.write("        <form class=\"form-horizontal\"\r\n");
      out.write("      name=\"myform\">\r\n");
      out.write("      \r\n");
      out.write("       <div class=\"form-group\">\r\n");
      out.write("          <label class=\"col-sm-3 control-label\" for=\"inputPassword\">의사</label>\r\n");
      out.write("        \t<div class=\"col-sm-6\">\r\n");
      out.write("          <input class=\"form-control\" id=\"doc_id\" name=\"doc_id\" type=\"text\" readonly=\"readonly\" value =\"");
      out.print(doc_id );
      out.write("\" >     \r\n");
      out.write("        \t</div>\r\n");
      out.write("        </div>\r\n");
      out.write("      \r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("          <label class=\"col-sm-3 control-label\" for=\"inputPassword\">환자ID</label>\r\n");
      out.write("        \t<div class=\"col-sm-6\">\r\n");
      out.write("          <input class=\"form-control\" id=\"id\" name=\"id\" type=\"text\" readonly=\"readonly\" value =\"");
      out.print(id );
      out.write("\" >     \r\n");
      out.write("        \t</div>\r\n");
      out.write("        </div>\r\n");
      out.write("  \r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("          <label class=\"col-sm-3 control-label\" for=\"inputPassword\">예약날짜</label>\r\n");
      out.write("        \t<div class=\"col-sm-6\">\r\n");
      out.write("          <input class=\"form-control\" id=\"date\" name=\"date\" type=\"text\" readonly=\"readonly\" value =\"");
      out.print(date );
      out.write("\" >     \r\n");
      out.write("        \t</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("          <label class=\"col-sm-3 control-label\" for=\"inputPassword\">환자이메일</label>\r\n");
      out.write("        \t<div class=\"col-sm-6\">\r\n");
      out.write("          <input class=\"form-control\" id=\"email\" name=\"email\" type=\"text\" readonly=\"readonly\" value =\"");
      out.print(email );
      out.write("\" >     \r\n");
      out.write("        \t</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("         <div class=\"form-group\">\r\n");
      out.write("            <label class=\"col-sm-3 control-label\" for=\"inputName\">진료과목</label>\r\n");
      out.write("          <div class=\"col-sm-6\">\r\n");
      out.write("            <input class=\"form-control\" id=\"subject\" name=\"subject\"  type=\"text\"  readonly=\"readonly\" value = \"");
      out.print(subject );
      out.write("\">\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("          <div class=\"col-sm-12 text-center\">\r\n");
      out.write("              <button class=\"btn btn-primary\" type=\"button\" onclick=\"javascript:submitForm(this.form,'admin_Doctor_Reservation_Update.jsp')\">수정<i class=\"fa fa-check spaceLeft\"></i></button>\r\n");
      out.write("            <button class=\"btn btn-primary\" type=\"button\"onclick=\"javascript:submitForm(this.form,'admin_Doctor_Reservation_DeletPro.jsp')\">삭제<i class=\"fa fa-check spaceLeft\"></i></button>\r\n");
      out.write("            <button class=\"btn btn-danger\" onclick=\"Windowclose();\">취소<i class=\"fa fa-check spaceLeft\"></i></button>\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        </form>\r\n");
      out.write("        \r\n");
      out.write("          <hr>\r\n");
      out.write("        </div>\r\n");
      out.write("      </article>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->\r\n");
      out.write("    <script src=\"../../assets/js/ie10-viewport-bug-workaround.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
