/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.33
 * Generated at: 2016-04-12 16:54:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class hello_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=EUC-KR\">\r\n");
      out.write("\t<meta name=\"description\" content=\"Cardio is a free one page template made exclusively for Codrops by Luka Cvetinovic\" />\r\n");
      out.write("\t<meta name=\"keywords\" content=\"html template, css, free, one page, gym, fitness, web design\" />\r\n");
      out.write("\t<meta name=\"author\" content=\"Luka Cvetinovic for Codrops\" />\r\n");
      out.write("\t<!-- Favicons (created with http://realfavicongenerator.net/)-->\r\n");
      out.write("\t<link rel=\"apple-touch-icon\" sizes=\"57x57\" href=\"img/favicons/apple-touch-icon-57x57.png\">\r\n");
      out.write("\t<link rel=\"apple-touch-icon\" sizes=\"60x60\" href=\"img/favicons/apple-touch-icon-60x60.png\">\r\n");
      out.write("\t<link rel=\"icon\" type=\"image/png\" href=\"img/favicons/favicon-32x32.png\" sizes=\"32x32\">\r\n");
      out.write("\t<link rel=\"icon\" type=\"image/png\" href=\"img/favicons/favicon-16x16.png\" sizes=\"16x16\">\r\n");
      out.write("\t<link rel=\"manifest\" href=\"img/favicons/manifest.json\">\r\n");
      out.write("\t<link rel=\"shortcut icon\" href=\"img/favicons/favicon.ico\">\r\n");
      out.write("\t<meta name=\"msapplication-TileColor\" content=\"#00a8ff\">\r\n");
      out.write("\t<meta name=\"msapplication-config\" content=\"img/favicons/browserconfig.xml\">\r\n");
      out.write("\t<meta name=\"theme-color\" content=\"#ffffff\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/normalize.css\">\r\n");
      out.write("\t<!-- Bootstrap -->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/bootstrap.css\">\r\n");
      out.write("\t<!-- Owl -->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/owl.css\">\r\n");
      out.write("\t<!-- Animate.css -->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/animate.css\">\r\n");
      out.write("\t<!-- Font Awesome -->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"fonts/font-awesome-4.1.0/css/font-awesome.min.css\">\r\n");
      out.write("\t<!-- Elegant Icons -->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"fonts/eleganticons/et-icons.css\">\r\n");
      out.write("\t<!-- Main style -->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/cardio.css\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"modal fade\" id=\"modal1\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("\t\t<div class=\"modal-dialog\">\r\n");
      out.write("\t\t\t<div class=\"modal-content modal-popup\">\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"close-link\"><i class=\"icon_close_alt2\"></i></a>\r\n");
      out.write("\t\t\t\t<h3 class=\"white\">Sign Up</h3>\r\n");
      out.write("\t\t\t\t<form action=\"\" class=\"popup-form\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"form-control form-white\" placeholder=\"Full Name\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"form-control form-white\" placeholder=\"Email Address\">\r\n");
      out.write("\t\t\t\t\t<div class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t<button id=\"dLabel\" class=\"form-control form-white dropdown\" type=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("\t\t\t\t\t\t\tPricing Plan\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu animated fadeIn\" role=\"menu\" aria-labelledby=\"dLabel\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"animated lightSpeedIn\"><a href=\"#\">1 month membership ($150)</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"animated lightSpeedIn\"><a href=\"#\">3 month membership ($350)</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"animated lightSpeedIn\"><a href=\"#\">1 year membership ($1000)</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"animated lightSpeedIn\"><a href=\"#\">Free trial class</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"checkbox-holder text-left\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"checkbox\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"checkbox\" value=\"None\" id=\"squaredOne\" name=\"check\" />\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"squaredOne\"><span>I Agree to the <strong>Terms &amp; Conditions</strong></span></label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<button type=\"submit\" class=\"btn btn-submit\">Submit</button>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t<script src=\"js/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/owl.carousel.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/wow.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/typewriter.js\"></script>\r\n");
      out.write("\t<script src=\"js/jquery.onepagenav.js\"></script>\r\n");
      out.write("\t<script src=\"js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
